# Generated by Django 5.2.7 on 2025-10-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_reads', to='api.proof')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proof_reads',
                'unique_together': {('proof', 'user')},
            },
        ),
    ]
