# Generated by Django 5.2.7 on 2026-05-23
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_verified'),
    ]

    operations = [
        # Drop the old ExchangeRate table if it exists
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_exchangerate;",
            reverse_sql="CREATE TABLE api_exchangerate (id integer PRIMARY KEY);"
        ),
        
        # Create the ExchangeRate table with correct structure
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source', models.CharField(help_text='e.g. Bank of Uganda, MTN, Forex API', max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exchange_rates', to='api.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_exchange_rates', to='api.currency')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        
        # Add the unique constraint
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency', 'valid_from'), name='unique_rate_per_period'),
        ),
    ]