# Generated by Django 5.2.7 on 2025-11-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_proof_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("receiver_name", models.CharField(max_length=255)),
                (
                    "receiver_contact",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=10)),
                (
                    "transaction_reference",
                    models.CharField(max_length=100, unique=True),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proof",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="api.proof",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
