# Generated by Django 5.2.7 on 2026-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_fix_exchangerate_structure"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chargerule",
            unique_together={("country", "currency")},
        ),
        migrations.AlterField(
            model_name="chargerule",
            name="charge_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterModelTable(
            name="chargerule",
            table="charge_rules",
        ),
        migrations.RemoveField(
            model_name="chargerule",
            name="charge_amount",
        ),
        migrations.RemoveField(
            model_name="chargerule",
            name="max_amount",
        ),
        migrations.RemoveField(
            model_name="chargerule",
            name="min_amount",
        ),
    ]
