# Generated by Django 5.2.7 on 2025-11-08 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
