# Generated by Django 5.2.7 on 2025-11-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_transaction_charge_amount_transaction_net_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proofs",
                to="api.country",
            ),
        ),
    ]
