# Generated by Django 5.2.7 on 2025-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_proof_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10, unique=True)),
                ("rate_to_ugx", models.DecimalField(decimal_places=4, max_digits=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
