# Generated by Django 5.2.7 on 2025-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
