# Generated by Django 5.2.7 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_announcement_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="company-images/"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="color",
            field=models.CharField(
                blank=True, default="#2196F3", max_length=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("info_outline", "Info Outline"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("location_on", "Location On"),
                    ("business", "Business"),
                    ("home", "Home"),
                    ("logo", "Logo"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("logo", "Logo"),
                    ("about", "About"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("address", "Address"),
                ],
                default="about",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="companyinfo",
            table=None,
        ),
    ]
