# Generated by Django 5.2.7 on 2025-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_companyinfo_logo_image_alter_companyinfo_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadProofStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("color", models.CharField(default="#2196F3", max_length=7)),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
    ]
