# Generated by Django 5.2.7 on 2025-12-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_whatsappcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="proof",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="api.proof",
            ),
        ),
    ]
