# Generated by Django 5.2.7 on 2025-12-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_transaction_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="color",
            field=models.CharField(default="#6c757d", max_length=7),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.country",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_currency",
            field=models.CharField(default="UGX", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ugx_equivalent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
